services:
  http-server:
    build:
      context: ..
      dockerfile: "docker/http-server"
    image: http-server:latest
    container_name: http-server
    ports:
      - 80:80
      - 443:443
    environment:
      - AUTH_USERNAME=${AUTH_USERNAME}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - DATABASE_URL=postgres://username:password@postgres:5432/postgres
    depends_on:
      - postgres

  postgres:
    build:
      context: ..
      dockerfile: "docker/postgres"
    image: http-server-postgres:latest
    container_name: http-server-postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    # ports:
    #   - "5432:5432"
    volumes:
      - http-server-postgres_data:/var/lib/postgresql/data

volumes:
  http-server-postgres_data:
